### ISSUE TITLE
Case error in RTClib.cpp

### ISSUE THREAD

**Issue by rabinnh** [adafruit/RTClib#10]
I was going a little nuts.  Using Arduino IDE 1.0, the compiler was complaining:

/usr/share/arduino/libraries/RTClib/RTClib.cpp:11:21: fatal error: arduino.h: No such file or directory
compilation terminated.

The error is in RTClib.h.  The following section attempts to include <arduino.h>:

```
#if ARDUINO > 22
#include <arduino.h>
#endif
```

This is a case error.  It should be:

```
#if ARDUINO > 22
#include <Arduino.h>
#endif
```

**Comment by muyoba** [comment]
hai guys.i have a problem with tis code.i copied it on circuit digest but its giving me error.
[attendance regiter.txt](https://github.com/adafruit/RTClib/files/1287744/attendance.regiter.txt)

**Comment by muyoba** [comment]
Hai guys. i have a problem with tis code. i copied it on circuit digest but its giving me error. help me rectify that error.rectify it send it to hmuyoba@gmail.com``
