### ISSUE TITLE
// Released to the public domain! Enjoy!

### ISSUE THREAD

**Issue by massimiliano-cannata** [adafruit/RTClib#100]
It is not really a license !!!! Can you provide a better indication of the type of license? GPLv2?
Other Adafriut lib have license selected in github, just create a new file "license.md" and select your preferred one....

_Originally posted by @massimiliano-cannata in https://github.com/adafruit/RTClib/issue_comments#issuecomment-424641843_

**Comment by ladyada** [comment]
public domain means you can use it for anything. if you really care about it, please submit a PR with a license file that contains a public domain license text and we'll merge it :)
