### ISSUE TITLE
Not working when compile for Raspberry2+, please help, thank you

### ISSUE THREAD

**Issue by Barabba11** [adafruit/RTClib#103]
Hi, I'm compinig with Arduino IDE directly to bin file for my Raspberry3. I have no issues with other I2C libraries, ADC, I/O, etc work fine, but I can't find an RTC lbrary compatible with Raspberry, 
exit status 1, "Errore durante la compilazione per la scheda RaspberryPI B+/2."

I just need to read the clock and store new values.. I;m very sad I can;t find nothing..  strange, I guess it's only a couple of I2C requests tothe device and read the answer, I'm thinking to lead datasheet DS3231 and send I2C commnds manually.
Kindly help me, thank you!

**Comment by ladyada** [comment]
yeah we dont support raspberry pi with this library *at all* :) please contact the vendor you bought your RTC from for support on getting it running with linux!
