### ISSUE TITLE
DS1307 example - wrong comment

### ISSUE THREAD

**Issue by JAY-M-ERICSSON** [adafruit/RTClib#104]
The comment

    // calculate a date which is 7 days and 30 seconds into the future
    DateTime future (now + TimeSpan(7,12,30,6));
    
[Line 52](https://github.com/adafruit/RTClib/blob/8ff0034c319b1b4126afcaba2c0b25c0f2f6f439/examples/ds1307/ds1307.ino#L52) 

Doesn’t match what the code does... now + 7days 12h 30min and 6sw

**Comment by da-vics** [comment]
Yes i noticed that also!

**Comment by drak7** [comment]
Fixed in #122
