### ISSUE TITLE
MKR Zero doesn't work with DS3231 RTC and RTClib

### ISSUE THREAD

**Issue by Bushedo** [adafruit/RTClib#110]
Have been trying to integrate DS3231 RTC to work with MKR Zero through the I2C bus without success. Programs compile and other units on the bus like a BME280 work.  When the I2C bus is scanned, the board returns the address of the RTC and its on-board memory chip. Used several DS3231 libraries including RTClib but none seem to work. After changing the date and time using the example code from the RTClib library (ds3231), the unit always returns the same date 2 Feb 2019 (yes, USA groundhog day!). The clock module works great with an Uno.  Suspect it could be a timing issue, but can't see any obvious suspects in the library source code.

**Comment by ladyada** [comment]
hiya, if no RTC lib works, then its somthing else? we've used this chip with M0 board plenty. could be something with pullup resistors, power, or if its a fake DS3231 (many low cost boards are).
