### ISSUE TITLE
No Movement on SDA1 SDL1

### ISSUE THREAD

**Issue by JPluess** [adafruit/RTClib#123]
Hi there, i use this library it works on Leonardo but on due it is very strange. 
i won’t get any stable readouts. it works sometimes. if it does not work the SDL1 and SCL1 stay high always. there is no clocking and data transmission. i checked with the oscilloscope. the controller is new. does anybody have an idea? i assume it can only be the library. since the example code does not run well.
i use it with a DS3231 clock.

**Comment by ladyada** [comment]
please contact your vendor for tech support :)
