### ISSUE TITLE
lostPower() for PCF8523

### ISSUE THREAD

**Issue by marcelstoer** [adafruit/RTClib#128]
For the DS3231 you support reading the stop flag as per https://github.com/adafruit/RTClib/blob/04182cbbc10b242513c598ce397babb00609bf93/RTClib.cpp#L963. This request is to add a similar function for PCF8523.

Relevant data sheet section: https://www.nxp.com/docs/en/data-sheet/PCF8523.pdf#page=9 and chapter 8.6.1.1.

Your Python implementation for reference is here https://github.com/adafruit/Adafruit-uRTC/blob/master/urtc.py#L210 and the one for CircuitPython is here https://github.com/adafruit/Adafruit_CircuitPython_PCF8523/blob/master/adafruit_pcf8523.py#L75.

**Comment by drak7** [comment]
Please submit a PR and we'll add it!

**Comment by colindgrant** [comment]
Hi @marcelstoer, I'm working with the PCF8523 RTC too, and I just submitted a PR for your issue. If you're interested in reviewing, I welcome your feedback. You can see the changes in 38a17a9 as part of #158.
