### ISSUE TITLE
Documenting how to use with ESP8266?

### ISSUE THREAD

**Issue by marcelstoer** [adafruit/RTClib#129]
If you use this with ESP8266 you need 

```c++
#include <Wire.h>
...
void setup () {
  Wire.begin(2, 14); // or some other pins
...
```

I was wondering if these two lines shouldn't be documented somewhere and/or be added as commented code to the example `.ino`s?

**Comment by siddacious** [comment]
That's a great idea! If you submit a pull request I'd be happy to review

**Comment by marcelstoer** [comment]
I later realized that the README contains a note around line 34 to that effect. Of course code is always better than documentation. I'll submit a PR.

**Comment by marcelstoer** [comment]
PR rejected -> closing
