### ISSUE TITLE
Can't build for nRF targets

### ISSUE THREAD

**Issue by caternuson** [adafruit/RTClib#136]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=25&t=163404

Related: 
https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/456

**Comment by drak7** [comment]
Solved in the forum thread! Upgrade to the latest (>= 0.19.0) nRF BSP.

**Comment by henrygab** [comment]
As was discovered, 0.19.0 release did not include the fix.  The commit occurred just after the 0.19.0 release was snap'd.  The next release should include the fix.
