### ISSUE TITLE
Error in pcf8523 example

### ISSUE THREAD

**Issue by DSiwi** [adafruit/RTClib#137]
Hello. I have just the rfc8523.ino example on an Adafruit RTC-Logger Feather board (#2922) and Programino IDE. 
However I quickly found that it would compile and load but not run, but instead locks up without anything apparent happening on the board.

I found that there is a problem at the start of this example program.

void setup () {

  while (!Serial) {
    delay(1);  // for Leonardo/Micro/Zero
  }

  Serial.begin(57600);
  if (! rtc.begin()) {
    Serial.println("Couldn't find RTC");
    while (1);
  }

No doubt you see it straight away. It is waiting for the Serial to be ready before initialising it.
I have looked at a couple of the other examples, but they do not have the same issue. I have not looked at them all.
Cheers,

**Comment by drak7** [comment]
Good catch! It probably slipped through the cracks and worked in some cases because Serial will always return true on boards that don't have native USB.
