### ISSUE TITLE
12 Hour Format Support

### ISSUE THREAD

**Issue by jadonmmiller** [adafruit/RTClib#140]
I'm working on a moderately sized project, and I'm considering modifying the DateTime class to support the twelve-hour format.

I'm thinking of storing the time internally in the 24hr format as it is now, but add an additional constructor with something like an *isPM* argument. (0 = AM, 1 = PM - true and false should also work.)
```C++
DateTime (uint16_t year, uint8_t month, uint8_t day,
                     uint8_t hour = 0, uint8_t isPM = 0,
                     uint8_t min = 0, uint8_t sec = 0);
```
I would also need to add another hour function that would return the hour with a range of 1-12, maybe something like this.
```C++
uint8_t twelveHour() const 
```
As well as an AM/PM function:
```C++
uint8_t isPM() const
```

I'm just wondering if there's any interest in this functionality, and if I do start working on it, any warnings or suggestions. Thanks, and feel free to tell me any ideas you have!

**Comment by drak7** [comment]
Closing this since we have #141
