### ISSUE TITLE
Support for EEPROM logging

### ISSUE THREAD

**Issue by docgmark** [adafruit/RTClib#142]
There is a DS3231_simple Library with great EEPROM logging capabilities:

https://github.com/sleemanj/DS3231_Simple/blob/master/DS3231_Simple.h

Whould it be possible to incorporate this part of the code to this library to extend the capabilities? The two libraries cannot coexist...

I would like to help, but my programming skills are very basic...

**Comment by drak7** [comment]
I think it's beyond the scope of this library. Logging capabilities aren't native to the RTC chips themselves (though the DS1307 does have some NVRAM storage) and the boards this is primarily targeted at don't have an EEPROM.

And that's just one chip, if we start down that road we end up with x, y, and z EEPROMS/flashes/etc and before you know it we have The One RTClib To Rule Them All but it's 8MB :)
