### ISSUE TITLE
Document how to kick system_tick() from an RTC on AVR

### ISSUE THREAD

**Issue by edgar-bonet** [adafruit/RTClib#165]
The canonical way to get the current time with RTClib seems to be by calling `rtc.now()`. This is a slow, blocking operation that requires an I2C data exchange. In contrast, [the avr-libc's &lt;time.h&gt;][avr] provides the standard function `time()`, which does little more than retrieve four bytes from RAM, and is thus extremely fast. However, in order to use `time()` and the related standard C timing functions, one has to:

1. Initialize the system time with `set_system_time()`. I doesn't hurt that the epoch of `time_t` in avr-libc is the same as the one of `DateTime::secondstime()`, namely the start of year 2000.
2. Call `system_tick()` every second, which is expected to be typically done from an ISR. The 1&nbsp;Hz “Second Timer” of the PCF8523 seems to be designed almost on purpose for this.

This approach is very efficient, as it only requires incrementing a global integer every second from an ISR, and reading it for getting the current time. Below is a test sketch demonstrating this approach:

```c++
#include <RTClib.h>
#include <time.h>

// Dummy implementation for non-AVR platforms.
#if !__AVR__
void set_system_time(time_t) {}
void system_tick() {}
#endif

const uint8_t pin1Hz = 2;  // pin receiving the 1 Hz interrupt

RTC_PCF8523 rtc;

void setup() {
    Serial.begin(9600);

    // Initialize the RTC.
    rtc.begin();
    if (!rtc.initialized() || rtc.lostPower())
        rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));
    rtc.deconfigureAllTimers();  // just in case

    // Initialize the system time from the RTC.
    set_system_time(rtc.now().secondstime());

    // Keep the time in sync using the 1 Hz output of the RTC.
    pinMode(pin1Hz, INPUT_PULLUP);
    rtc.enableSecondTimer();
    attachInterrupt(digitalPinToInterrupt(pin1Hz), system_tick, FALLING);
}

void loop() {
    time_t now = time(nullptr);
    Serial.println(asctime(gmtime(&now)));
    delay(1000);
}
```

I now have the following questions:

1. Is it worth documenting this approach?
2. If so, what would be the right place(s) to do so? A .dox file that doxygen would include in the reference documentation? An example sketch? Both? A short note in the README pointing to either?
3. What about the non-AVR targets? Could this technique be easily applied to them? The [documentation of newlib's `time()`][newlib] (that's the libc used for SAMD, right?) only states that “Some implementations require `gettimeofday`.
4. If this is going to be AVR-only, how to avoid the CI pipeline reporting a breakage on non-AVR targets? Is the conditional compilation of dummy functions, as show above, an acceptable solution? It seems the CI script has [provisions for skipping some platform builds][skip]. Has this been tested? Is it a better approach?

I checked that newlib provides the standard &lt;time.h&gt; functions `time()`, `gmtime()` and `asctime()`, but not the AVR-specific `set_system_time()` and `system_tick()`. It would not be too hard to implement them, but that would require re-implementing `time()`. Wouldn't that be too much for an example sketch?

[avr]: https://www.nongnu.org/avr-libc/user-manual/group__avr__time.html
[newlib]: https://sourceware.org/newlib/libc.html#time
[skip]: ../../ci-arduino/blob/37dc6a11467f25e26f81db2022e60473b2e69d1f/build_platform.py#L183-L191

**Comment by drak7** [comment]
I think it'd be worth an example sketch demonstrating it. You can skip the non-AVR platforms in CI by including a skip file in the example, check out the [GPS library examples](https://github.com/adafruit/Adafruit_GPS/tree/master/examples) to see that.
