### ISSUE TITLE
new feature: Arduino Simulator link for RTClib examples 🙂

### ISSUE THREAD

**Issue by matititam** [adafruit/RTClib#216]
1. https://wokwi.com/arduino/projects/286712672726024717
2. https://wokwi.com/arduino/projects/286713783510893069
3. https://wokwi.com/arduino/projects/286714510843052556
4. https://wokwi.com/arduino/projects/286719428789273101

I have added the links.

Kindly give some time, while I create permanent links for other RTCLib Arduino examples.
Once done, I will give a hint here again.

Many thanks

Meanwhile, if you have any feedback, kindly share.

**Comment by caternuson** [comment]
Thanks. Looks cool. These issues are for posting problems specific to this library repo.
