### ISSUE TITLE
PCF8523 issues with version 1.13.0, works with 1.11.4

### ISSUE THREAD

**Issue by dfontenot** [adafruit/RTClib#232]
- Arduino board:  **Arduino pro mini**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.13**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):
* Download RTClib 1.13 using Arduino package manager
* Upload example code (from the Arduino menu) for the PCF8523 module
* Message from serial monitor says "Couldn't find RTC"
* Drop down to version 1.11.4 of RTClib using the package manager (did not try all versions prior to 1.13.0, there may be a newer one that still works)
* Upload that version's example program
* Confirm in the messages I am now able to see a date of 2004/5/9 13:40:2

It looks like there's a problem with the latest RTClib version in the Arduino package manager (or maybe just a problem with the example program). I am following along with [this Adafruit guide](https://learn.adafruit.com/adafruit-pcf8523-real-time-clock/rtc-with-arduino). The module I am using is an Adafruit assembled PCF8523 module.

**Comment by caternuson** [comment]
Try again with latest release which changed up a lot of the I2C plumbing. Can reopen if problem still exists.
