### ISSUE TITLE
DS3231 on RTCLib giving incorrect signals to RP2040

### ISSUE THREAD

**Issue by KineticLabs25** [adafruit/RTClib#233]
- Arduino board:  Adafruit Feather RP2040 with DS3231 featherwing

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.15

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

- Using the "ds3231" example code in RTCLib with the RP2040 feather and earlephilhower RP2040 core, I receive this in the serial monitor: 
<img width="376" alt="Screen Shot 2021-07-03 at 3 03 45 PM" src="https://user-images.githubusercontent.com/79662454/124365836-416a3900-dc10-11eb-98f8-59b3ef7da4f4.png">

- By switching over to a feather express M0+ with the adafruit SAMD core, and changing nothing within the code I receive this:
<img width="384" alt="Screen Shot 2021-07-03 at 3 08 29 PM" src="https://user-images.githubusercontent.com/79662454/124365867-8d1ce280-dc10-11eb-951f-5d458a8c4c4e.png">

I'm not sure what's causing the issue, the core or the library, but the signal seems to be getting a little confused. Time updates and everything runs with no issue on the M0+, but doesn't seem to be friendly with the RP2040 right now. I would appreciate someone a little smarter than me taking a look!

**Comment by caternuson** [comment]
Try again with latest RTC library release and RP2040 BSP.

Note that you likely need to change the wire instance being passed in to begin to access the Feather RP2040's SCL/SDA pins:
```cpp
  if (! rtc.begin(&Wire1)) {
```

Just tested on a Feather RP2040 using SCL/SDA header pins (not STEMMA) and seems to run OK:
![Screenshot from 2021-11-02 13-25-06](https://user-images.githubusercontent.com/8755041/139946835-d51a5c57-ca99-4bfd-9dee-290ea5b5b725.png)
