### ISSUE TITLE
Unix timestamp bug!?!

### ISSUE THREAD

**Issue by Athanasioschourlias** [adafruit/RTClib#286]
- Arduino board:  RTC PCF8523

- Arduino IDE version (found in Arduino -> About Arduino menu):  
Version: 2.1.0
Date: 2023-04-19T15:26:42.115Z
CLI Version: 0.32.2

- Possible bug -> 
Hey, since this is the first time im playing around with RTC modules please take it easy on me.

Now that's out of the way, i noticed something strange while setting up my RTC module, when i run the example code, as suggested in the docs, in order to set up the local time in my module i get back a perfect fine date and time to the second, but when i run the function to get back the Unix time i have an offset of +3 hours. For example, the time function says it is (21:51:37, in Greece) and almost to the second it is correct, but the Unix time(1685656619) does not represent the time that is printed out.
this is the code i used

\`
#include "RTClib.h"

void setup() {

  if (! rtc.begin()) {
    Serial.println("Couldn't find RTC");
    Serial.flush();
    while (1) delay(10);
  }

  Serial.begin(57600);
  rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));
  rtc.start();

}

void loop() {
   DateTime now = rtc.now();

   Serial.print(now.year(), DEC);
   Serial.print('/');
   Serial.print(now.month(), DEC);
   Serial.print('/');
   Serial.print(now.day(), DEC);
   Serial.print(" (");
   Serial.print(daysOfTheWeek[now.dayOfTheWeek()]);
   Serial.print(") ");
   Serial.print(now.hour(), DEC);
   Serial.print(':');
   Serial.print(now.minute(), DEC);
   Serial.print(':');
   Serial.print(now.second(), DEC);
   Serial.println();

   Serial.print(" since midnight 1/1/1970 = ");
   Serial.println(now.unixtime());

}
\`

But its gets stranger. When i moved to Sweden from Greece i noticed that the Unix time difference became 2 instead of 3 hours.

The question here is. Can that be a bug where the developers are calculating the time and then take into account the timezone and adding or decreasing some extra hours, for example in Greece 3 hours, or i missed something?

**Comment by edgar-bonet** [comment]
This is a known limitation of the library. From the [documentation of the DateTime class][doc]:

> The class has no notion of time zones, daylight saving time, or leap seconds: time is stored in whatever time zone the user chooses to use.

This means that the `unixtime()` method cannot account for your timezone, and thus does not return a proper Unix time. This is more clearly stated in the documentation of the constructor from “Unix time”:

> This number is analogous to Unix time, with two small differences:
> * The Unix epoch is specified to be at 00:00:00 UTC, whereas this class has no notion of time zones. The epoch used in this class is then at 00:00:00 on whatever time zone the user chooses to use, ignoring changes in DST. [...]

You wrote:
> Can that be a bug where the developers are calculating the time and then take into account the timezone

Quite the contrary. The issue is that the library **fails** to take into account the timezone, simply because it doesn't know it (and wouldn't want to handle the complexities of timezones anyway).

[doc]: https://adafruit.github.io/RTClib/html/class_date_time.html

**Comment by Athanasioschourlias** [comment]
Oh thank youy, ngl i did not dive that deep to the doc's.
