### ISSUE TITLE
Shouldn't need wire.h for softrtc.ino example

### ISSUE THREAD

**Issue by Scott216** [adafruit/RTClib#30]
Since the softrtc.ino example ins't communicating with a RTC device, I don't think you should need wire.h library.  When I commented it out I got a bunch of errors.  Most of them I solved by adding 
```
#include <inttypes.h>
```
But I still get an error on RTClib.h, line 17:
```
DateTime (const __FlashStringHelper* date, const __FlashStringHelper* time);
```
I'm not sure how to fix that one.

**Comment by ladyada** [comment]
hiya pardon the late reply. #include <Arduino.h> has been added, but you still need #include <wire.h> because that library is not used but still 'depended on' by RTClib (its a Thing with the arduino IDE)
