### ISSUE TITLE
bug of incompatibility with the library time.h

### ISSUE THREAD

**Issue by icnmfabro** [adafruit/RTClib#35]
I wanted to point out that the library RTClib.h not fully compatible with the library Time.h.
The incompatibility is caused by the function dayOfWeek () because also the other library has the same function. Personally, I solved the problem by renaming the function dayOfWeek () with dayOfWeekRtc ().

Hoping that the bug report can be of help, Best regards and good in 2015.

**Comment by ladyada** [comment]
pardon the delay - did a sweep of this library and fixed this!

**Comment by icnmfabro** [comment]
Excellent  :-)
