### ISSUE TITLE
RTClib fails to compile on Arduino Zero and Intel-based (Galileo, Edison)

### ISSUE THREAD

**Issue by feranick** [adafruit/RTClib#44]
Using IDE 1.6.5, with latest RTClib installed. In my sketch, I used RTClib and my sketch works well, let alone compile fine. However, when I try to compile it targeting Arduino Zero I get this:

/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In member function 'uint8_t RTC_DS1307::isrunning()':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:228:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function 'static void RTC_DS1307::adjust(const DateTime&)':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:238:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function 'static DateTime RTC_DS1307::now()':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:252:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function 'static Ds1307SqwPinMode RTC_DS1307::readSqwPinMode()':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:271:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function 'static void RTC_DS1307::writeSqwPinMode(Ds1307SqwPinMode)':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:283:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In member function 'void RTC_DS1307::readnvram(uint8_t*, uint8_t, uint8_t)':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:291:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In member function 'void RTC_DS1307::writenvram(uint8_t, uint8_t*, uint8_t)':
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:12:15: error: 'Wire1' was not declared in this scope
  #define WIRE Wire1
               ^
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:303:3: note: in expansion of macro 'WIRE'
   WIRE.beginTransmission(DS1307_ADDRESS);
   ^
Error compiling.

When I compile it against any of the Intel based Arduinos I get:

Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In member function ‘uint8_t RTC_DS1307::isrunning()’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:228:3: error: ‘Wire1’ was not declared in this scope
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function ‘static void RTC_DS1307::adjust(const DateTime&)’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:238:3: error: ‘Wire1’ was not declared in this scope
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function ‘static DateTime RTC_DS1307::now()’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:252:3: error: ‘Wire1’ was not declared in this scope
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function ‘static Ds1307SqwPinMode RTC_DS1307::readSqwPinMode()’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:271:3: error: ‘Wire1’ was not declared in this scope
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In static member function ‘static void RTC_DS1307::writeSqwPinMode(Ds1307SqwPinMode)’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:283:3: error: ‘Wire1’ was not declared in this scope
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In member function ‘void RTC_DS1307::readnvram(uint8_t*, uint8_t, uint8_t)’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:291:3: error: ‘Wire1’ was not declared in this scope
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp: In member function ‘void RTC_DS1307::writenvram(uint8_t, uint8_t*, uint8_t)’:
/Applications/Arduino.app/Contents/Java/libraries/RTClib/RTClib.cpp:303:3: error: ‘Wire1’ was not declared in this scope
Error compiling.

**Comment by ladyada** [comment]
Pardon the delay, I believe this is fixed now - I ran the ds1307 demo on a Zero - make sure you are using arduino.cc not .org IDE! you may need to 'reprogram the bootloader' via EDBG to do so. (see burn the bootloader on https://www.arduino.cc/en/Main/ArduinoBoardZero)

**Comment by feranick** [comment]
Thanks!!!
