### ISSUE TITLE
+ operator for DateTime with Timespan (rvalue) seems to be dysfunctional.

### ISSUE THREAD

**Issue by Oligodendrogliom** [adafruit/RTClib#45]
I'm having the following code as part of my own class:

    DateTime TimeKeep::nowUTC()
    {
    	return rtc.now();
    }
    
    DateTime TimeKeep::now()
    {
    	return rtc.now()+TimeSpan(0, dst+tz/4, tz%4, 0);
    }

while rtc is of type RTC_DS1307 and dst=1 and tz=4. I checked for TimeSpan::totalseconds() returning the 7200 seconds correctly. But the outcome of my now() function gets wrong.

    	DateTime dt=TimeKeep::now();
	Serial.print("."); Serial.print(dt.year()); Serial.print("."); Serial.print(dt.month()); Serial.print("."); Serial.print(dt.day());
	Serial.print("-"); Serial.print(dt.hour()); Serial.print(":"); Serial.print(dt.minute()); Serial.print(":"); Serial.print(dt.second());
	dt=TimeKeep::nowUTC();
	Serial.print("."); Serial.print(dt.year()); Serial.print("."); Serial.print(dt.month()); Serial.print("."); Serial.print(dt.day());
	Serial.print("-"); Serial.print(dt.hour()); Serial.print(":"); Serial.print(dt.minute()); Serial.print(":"); Serial.print(dt.second());

This code yields for a given time:

    2043.4.30-11:16:56.2000.0.0-15:45:12

The wrong addition of TimeSpan is consistent. The interval between both DateTime is always the same.

**Comment by ladyada** [comment]
im not 100% up on my C++ memory trix, but i am pretty sure your TimeKeep function is creating a DateTime object on the stack, and when it returns, that memory is trashed. Especially with Arduino, this is particularly difficult to manage memory. what you might want to do is return the unixtime() which is a 32 bit int, then you are passing by value, no memory usage.
