### ISSUE TITLE
Adjusting the time switch off SQW

### ISSUE THREAD

**Issue by bbird1980** [adafruit/RTClib#46]
Hello, trying on my ArduinoUno with I2C DS1307 RTC:

      void setup() { 
            Wire.begin();
            rtc.begin();  
            rtc.writeSqwPinMode(SquareWave1HZ);
      }

Next in main loop triggered by push button doing a clock adjust by 10 seconds:
      DateTime newDateTime = rtc.now() + TimeSpan(0, 0, 0, 10);
      Serial.println(rtc.readSqwPinMode()); // => 16
      rtc.adjust(newDateTime);
      Serial.println(rtc.readSqwPinMode()); // => 0

So after adjusting Sqw switching off...

**Comment by ladyada** [comment]
hey you're right! fixed :)
