### ISSUE TITLE
Code not working with Arduino Due

### ISSUE THREAD

**Issue by scumulder** [adafruit/RTClib#73]
- Arduino board:  Arduino Due

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6.12

- I'm using an old datalogger shield with my Arduino Due. I am unable to set the current time on the RTC using rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));

My serial monitor keeps showing the following output:

![untitled](https://cloud.githubusercontent.com/assets/18566314/20904381/438c34dc-bb0d-11e6-9972-c3216e889c42.jpg)

**Comment by cwt137** [comment]
I get the same output when using a PCF8523 and an Arduino UNO R3 compatible device. Am I doing something wrong? I'm new to Arduino programming and building circuits.

**Comment by melucas** [comment]
I'm getting the same message "RTC is not running" and I can not set the time on the board.  

I have an Arduino UNO R3 board connected to a ZS-042 clock shield.

Clock SDA connected to Pin 20 on UNO
Clock SCL connected to Pin 21 on UNO

Any suggestions on how to resolve this?

**Comment by Spomky** [comment]
Hi @scumulder,

I have the same issue with my Arduino Due board.
Did you fixed it? If yes how did you managed that?

Regards

**Comment by melucas** [comment]
Hi @Spomky,

I got it working using the SDA1 and SCL1 pins on my  DUE board.

**Comment by messmerd** [comment]
I received the same error with the Due, so I commented out the line: 
`#define Wire Wire1`
in the library's .cpp file, and wired it up to use SDA and SCL, and it worked fine. 
I think I also had to remove the button cell battery of my RTC to make it lose power, then put it back in.

**Comment by drak7** [comment]
Sounds like a wiring issue, the library uses Wire1 (SDA1/SCL1) on Due by default.
