### ISSUE TITLE
RTC_Millis instances share offset

### ISSUE THREAD

**Issue by KensCode** [adafruit/RTClib#75]
- Arduino board:  Feather M0 WINC1500 (3010)
- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6.13
- List the steps to reproduce the problem below:

The definition of offset in RTC_Millis as static means that all instances of a millis-based clock share the same offset: adjust one, and they all change.  That might be intentional, although if so it doesn't appear to be documented.  But it means that two clocks showing different times can't be created, something I needed to do when working on calculating compensation for the drift of millis relative to real time.

**Comment by caternuson** [comment]
I think this is fixed now. Current class definition does not use static.
