### ISSUE TITLE
Issue with GSM Library

### ISSUE THREAD

**Issue by RadioMCMLVI** [adafruit/RTClib#83]
Hello,
I have a Home automation project with Remote Control using Arduino GSM board and a DS1307 RTC module. GSM Library is V1.0.6
A few weeks ago, I upgraded RTClib V1.0.0 to V1.2.0 and have this issue when compiling :
_### In file included from /home/robert/Arduino/MySketchsLibs/GSMRemoteControl/GSMRemoteControl.ino:64:0:
/home/robert/Arduino/libraries/RTClib-1.2.0/RTClib.h:79:31: error: redeclaration of 'OFF'
 enum Ds1307SqwPinMode { OFF = 0x00, ON = 0x80, SquareWave1HZ = 0x10, SquareWave4kHz = 0x11, SquareWave8kHz = 0x12, SquareWave32kHz = 0x13 };
                               ^
In file included from /home/robert/arduino-1.8.3-linux64/libraries/GSM/src/GSM3MobileNetworkProvider.h:37:0,
                 from /home/robert/arduino-1.8.3-linux64/libraries/GSM/src/GSM3MobileClientService.h:37,
                 from /home/robert/arduino-1.8.3-linux64/libraries/GSM/src/GSM.h:42,
                 from /home/robert/Arduino/MySketchsLibs/GSMRemoteControl/GSMRemoteControl.ino:62:
/home/robert/arduino-1.8.3-linux64/libraries/GSM/src/GSM3MobileAccessProvider.h:37:100: note: previous declaration 'GSM3_NetworkStatus_t OFF'
 enum GSM3_NetworkStatus_t { ERROR, IDLE, CONNECTING, GSM_READY, GPRS_READY, TRANSPARENT_CONNECTED, OFF};
                                                                                                    ^
exit status 1_###

I downgraded RTClib V1.2.0 to 1.1.0, same issue. Downgrading to V1.0.0 solves the problem.

By analysing RTClib.h, we have :

V1.0.0
_### // RTC based on the DS1307 chip connected via I2C and the Wire library
enum Ds1307SqwPinMode { Off = 0x00, On = 0x80, SquareWave1HZ = 0x10, SquareWave4kHz = 0x11, SquareWave8kHz = 0x12, SquareWave32kHz = 0x13 };_###

V1.1.0
_### // RTC based on the DS1307 chip connected via I2C and the Wire library
enum Ds1307SqwPinMode { OFF = 0x00, ON = 0x80, SquareWave1HZ = 0x10, SquareWave4kHz = 0x11, SquareWave8kHz = 0x12, SquareWave32kHz = 0x13 };_###

V1.2.0
_### // RTC based on the DS1307 chip connected via I2C and the Wire library
enum Ds1307SqwPinMode { OFF = 0x00, ON = 0x80, SquareWave1HZ = 0x10, SquareWave4kHz = 0x11, SquareWave8kHz = 0x12, SquareWave32kHz = 0x13 };_###

In V1.1.0 and V1.2.0, "OFF" and "ON" are full uppercase but not in V1.0.0. It seems this is the origin of the problem.

I have unfortunately enough experience to modify a library and so solve the problem in RTClib V1.2.0

Regards.
Robert.

**Comment by drak7** [comment]
Fixed in 1.2.4, these are now prefixed with DS1307_.
