### ISSUE TITLE
DUE DS1307 EEPROM Write and Read

### ISSUE THREAD

**Issue by miladamirzadeh** [adafruit/RTClib#87]
- Arduino board:  **DUE**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.5**

Hello dear developers,
I am working on the DUE board and trying to port my old application to this board. It seems because DUE is based on ARM it doesn't have EEPROM. I have heard that DS1307(which uses 24c32) can support EEPROM write and read. Can such a feature become available in RTClib.

There is a library called uRTClib that have functions to work with EEPROM on DS1307, but didn't work for me; Read always returns 0xFF.

**Comment by drak7** [comment]
This is now implemented, check out the readnvram/writenvram methods. There are 56 bytes available on the DS1307.
