### ISSUE TITLE
Working correction for issue #81 and added function as proposed in issue #86

### ISSUE THREAD

**Issue by eriktheV-king** [adafruit/RTClib#88]
The corrected .cpp file adding the readSqwPinMode() function in the DS3231 part of the .cpp file as proposed in issue #81 bugged when I tried to compile.

I managed to get it working as follows:
https://github.com/eriktheV-king/RTClib-from-Adafruit/blob/master/RTClib.cpp
-----------------------------------------------------------------------------------------
Ds3231SqwPinMode RTC_DS3231::readSqwPinMode() {
int mode;

Wire.beginTransmission(DS3231_ADDRESS);
Wire._I2C_WRITE(DS3231_CONTROL);
Wire.endTransmission();

Wire.requestFrom((uint8_t)DS3231_ADDRESS, (uint8_t)1);
mode = Wire._I2C_READ();

//mode &= 0x93;//bug due to using ds1307 read mask
mode &= 0x1C;
if(mode == 0x04)
mode = DS3231_OFF;
return static_cast<Ds3231SqwPinMode>(mode); // instead of "return static_cast(mode);"
}
-----------------------------------------------------------------------------------------

In the mean time, I also added the code for the .isrunning() function for DS3231 as proposed in issue # 86 and everything is now working perfectly well !

**Comment by caternuson** [comment]
I think this was fixed by #210.
